version: "3"
services:
  python:
    build: ./
    extra_hosts:
      - "host_machine:192.168.1.103" # 此处请填写宿主机的ip,方便容器访问宿主机
    volumes:
      - ./program:/program
#    command: python main.py
#    tty: true
    restart: always

  mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
#    restart: always
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
    ports:
    - 3306:3306