version: "3"
services:
  python:
    build: ./docker
    volumes:
      - ./program:/program
#    command: python main.py
#    tty: true
    links:
      - mysql

  mysql:
    image: mysql:5.6
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_DATABASE=default
      - MYSQL_USER=default
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=root
      - TZ=Asia/Shanghai
    ports:
    - 3306:3306